print('+---------------------------------------------------------------------+')
print('|                                                          June 2025  |')
print('|                                                        Raipur , CG  |')
print('|  Dear Self,                                                         |')
print('|                                                                     |')
print('|      Build the best AI models in the future & to become             |')
print('|      financially independent and a owner of net worth               |')
print('|      of atleast 1000 CRORES.                                        |')
print('|      Gonna be always grateful for what i have today                 |')
print('|      And will always be what i will have tomorrow.                  |')
print('|                                                                     |')
print('|                                              Brat Coder             |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')